name: publish-sdk

on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    # Only run for SDK releases
    if: startsWith(github.event.release.tag_name, '@selling-partner-api/sdk@')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.release.tag_name }}
          submodules: recursive
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.23"

      - name: Setup Node for npm publish
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run lint checks
        run: bun run lint

      - name: Build packages
        run: bun run build

      - name: Run unit tests with coverage
        run: bunx vitest run --coverage

      - name: Validate version
        run: |
          TAG="${{ github.event.release.tag_name }}"
          VERSION="${TAG#@selling-partner-api/sdk@}"
          PACKAGE_VERSION=$(node -p "require('./packages/sdk/package.json').version")
          
          if [ "${PACKAGE_VERSION}" != "${VERSION}" ]; then
            echo "Version mismatch: tag has ${VERSION} but package.json has ${PACKAGE_VERSION}" >&2
            exit 1
          fi
          
          echo "Version validated: ${VERSION}"

      - name: Wait for models dependency on npm
        run: |
          REQUIRED_VERSION=$(node -p "require('./packages/sdk/package.json').dependencies['@selling-partner-api/models']")
          # Remove ^ or ~ or other semver prefixes
          REQUIRED_VERSION="${REQUIRED_VERSION#^}"
          REQUIRED_VERSION="${REQUIRED_VERSION#~}"
          REQUIRED_VERSION="${REQUIRED_VERSION#>=}"
          
          echo "Checking if @selling-partner-api/models@${REQUIRED_VERSION} is available on npm..."
          
          attempts=0
          max_attempts=30
          sleep_seconds=10
          
          while [ $attempts -lt $max_attempts ]; do
            if npm view "@selling-partner-api/models@${REQUIRED_VERSION}" version &>/dev/null; then
              echo "✓ @selling-partner-api/models@${REQUIRED_VERSION} is available"
              break
            fi
            
            attempts=$((attempts + 1))
            echo "Attempt ${attempts}/${max_attempts}: Package not yet available, waiting ${sleep_seconds}s..."
            sleep $sleep_seconds
          done
          
          if [ $attempts -ge $max_attempts ]; then
            echo "Timed out waiting for @selling-partner-api/models@${REQUIRED_VERSION}" >&2
            exit 1
          fi

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}
        run: |
          cd packages/sdk
          npm publish --provenance --access public

      - name: Setup Node for GitHub Packages
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com"
          scope: "@selling-partner-api"

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd packages/sdk
          npm publish --provenance --access public
