name: publish-sdk

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'sdk-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.23"

      - name: Setup Node for npm publish
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run lint checks
        run: bun run lint

      - name: Build SDK package
        run: bun run build:sdk

      - name: Run unit tests
        run: bun test packages/sdk

      - name: Ensure beta prerelease version
        run: |
          VERSION=$(node -p "require('./packages/sdk/package.json').version")
          if [[ ${VERSION} != *-beta* ]]; then
            echo "Expected @selling-partner-api/sdk version to include '-beta' but found ${VERSION}" >&2
            exit 1
          fi

      - name: Log package version
        run: node -p "require('./packages/sdk/package.json').version"

      - name: Verify npm token configured
        run: |
          if [ -z "${NPM_TOKEN:-}" ]; then
            echo "NPM_TOKEN secret must be configured in the repository settings" >&2
            exit 1
          fi

      - name: Publish @selling-partner-api/sdk to npm
        run: |
          cd packages/sdk
          export NODE_AUTH_TOKEN="${NPM_TOKEN}"
          npm publish --provenance --access public --tag beta
