name: release-please

on:
  push:
    branches:
      - main
    paths:
      - 'packages/models/**'
      - 'packages/sdk/**'
      - '.release-please-manifest.json'
      - 'release-please-config.json'
      - '.github/workflows/release-please.yaml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

